### ISSUE TITLE
当ttl设置为0时，redis会返回“ERR invalid expire time in set”，不是forever

### ISSUE THREAD

**Issue by dingdinghappy** [devfeel/cache#5]
// Set cache to redis.
// ttl is second, if ttl is 0, it will be forever.
func (ca *redisCache) Set(key string, value interface{}, ttl int64) error {
	client := internal.GetRedisClient(ca.serverUrl, ca.maxIdle, ca.maxActive)
	_, err := client.SetWithExpire(key, value, ttl)
	return err
}

当过期时间设置为0时，redis会返回“ERR invalid expire time in set”，不是forever

**Comment by devfeel** [comment]
thanks. now it's fixed on Version 0.6.1
