### ISSUE TITLE
是否可以对外暴露一个设置key超时函数，hash key没有超时函数

### ISSUE THREAD

**Issue by dingdinghappy** [devfeel/cache#6]

**Comment by devfeel** [comment]
you can use Expire(key string, timeOutSeconds int) (int, error)
now it's supported on version 0.6.2

**Comment by dingdinghappy** [comment]
在cache.go的RedisCache interface {}接口中并没有暴露Expire()，从外层调用不到超时函数。

**Comment by devfeel** [comment]
RedisCache包含了Cache interface，而在Cache中已经定义了Expire接口：
// Expire Set a timeout on key. After the timeout has expired, the key will automatically be deleted.
// timeout time duration is second
Expire(key string, timeOutSeconds int) (int, error)

所以，你可以正常调用Expire例如：
redisCache := cache.GetRedisCache("redis://192.168.8.175:6379/0")
redisCache.HSet("hsettest", "keytest", "1")
redisCache.Expire("hsettest", 60)
