### ISSUE TITLE
可以增加一个发布订阅的接口吗

### ISSUE THREAD

**Issue by dingdinghappy** [devfeel/cache#7]

**Comment by devfeel** [comment]
now is support on version 0.6.6
#### Version 0.6.6
* New Command: RedisCache.Publish(channel string, message interface{})(int64, error)
* New Command: RedisCache.Subscribe(receive chan redis.Message, channels ...interface{})error
* 2018-08-03 11:00

**Comment by devfeel** [comment]
you can view test case in file: redis.cache_redis_test.go
